# Generated by Django 4.1.6 on 2023-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=70)),
                ('user_password', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=11)),
                ('user_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
