# Generated by Django 4.1.6 on 2023-02-18 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=29)),
                ('last_name', models.CharField(max_length=28)),
                ('user_email', models.EmailField(max_length=70)),
                ('user_password', models.CharField(max_length=150)),
                ('user_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='wrong number', regex='^(01)[0125][0-9]{8}$')])),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
