# Generated by Django 4.1.6 on 2023-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
