# Generated by Django 4.1.6 on 2023-02-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_image',
            field=models.ImageField(default=1, upload_to='uploads/users/'),
            preserve_default=False,
        ),
    ]
