# Generated by Django 4.1.6 on 2023-02-16 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_registeruser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid mobile phone number', regex='^(010 | 011 | 012 )[0-9]{8}$')]),
        ),
    ]
