# Generated by Django 4.1.6 on 2023-02-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_registeruser_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='user_password',
            new_name='set_password',
        ),
    ]
