# Generated by Django 4.1.6 on 2023-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_registeruser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='facebook_profile',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_image',
            field=models.ImageField(upload_to='uploads/users/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_mobile',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
