# Generated by Django 4.1.6 on 2023-02-16 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_registeruser_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='wrong number', regex='^(010 or 011 or 012 or 015)[0-9]{8}$')]),
        ),
    ]
