# Generated by Django 4.1.6 on 2023-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_registeruser_birthdate_registeruser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
