# Generated by Django 4.1.6 on 2023-02-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_user_password_registeruser_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='set_password',
            new_name='user_password',
        ),
    ]
