# Generated by Django 4.1.6 on 2023-02-16 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_registeruser_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='wrong number', regex='^(01)[0-9]{9}$')]),
        ),
    ]
