# Generated by Django 4.1.6 on 2023-02-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_registeruser_birthdate_registeruser_country_and_more'),
        ('auth_app', '0006_alter_registeruser_user_password'),
    ]

    operations = [
    ]
