# Generated by Django 4.1.6 on 2023-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
