# Generated by Django 4.1.6 on 2023-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_remove_reply_created_at_alter_commentreport_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='report',
        ),
    ]
